### ISSUE TITLE
The menu has some strange empty space at the bottom on mobile

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle-rs.github.io#238]
Here:

![Screenshot_20240216-141307](https://github.com/ruffle-rs/ruffle-rs.github.io/assets/288816/a62605e1-eb20-48c8-b4b9-7ed7811c375a)

I don't know why it's there, but doesn't seem necessary.
Not a big deal though!

**Comment by danielhjacobs** [comment]
The default style for that content area in the mantine Drawer is 
```css
height: var(--drawer-height, calc(100% - var(--drawer-offset) * 2));
```
As defined in https://github.com/mantinedev/mantine/blob/43c91731d52c416be7486c310fae04546caa1f9f/packages/%40mantine/core/src/components/Drawer/Drawer.module.css#L17

The default `--drawer-offset` is `0rem`, as defined in https://github.com/mantinedev/mantine/blob/7b1457f9eb084f0fb663c25793d08877cc957db0/packages/%40mantine/core/src/components/Drawer/Drawer.module.css#L8

The default `--drawer-height` is `--drawer-size` when `position` is not 'right' or 'left': https://github.com/mantinedev/mantine/blob/7b1457f9eb084f0fb663c25793d08877cc957db0/packages/%40mantine/core/src/components/Drawer/DrawerRoot.tsx#L104-L105

The default `--drawer-size` is `--drawer-size-md` according to https://github.com/mantinedev/mantine/blob/43c91731d52c416be7486c310fae04546caa1f9f/packages/%40mantine/core/src/components/Drawer/Drawer.module.css#L7

The default `--drawer-size-md` is `rem(440px)` according to https://github.com/mantinedev/mantine/blob/43c91731d52c416be7486c310fae04546caa1f9f/packages/%40mantine/core/src/components/Drawer/Drawer.module.css#L4

The rem is `16px`, so that's `27.5rem`. So that's the height of the mantine Drawer content area by default. I opened a PR to make it's height auto instead.

**Comment by torokati44** [comment]
Yay, thanks for the fix! ☺️
